### ISSUE TITLE
Add reminder to !poll/!pol command after it is created

### ISSUE THREAD

**Issue by stillatwork** [chatrealm/dctvbot#1]
I recommend the poll/pol command auto reminds the room every 5 minutes say 3 times (5, 10, and 15) so it advertises the poll to the users over time 

If 5 minutes is too long, feel free to shorted it, but no less than 1 minute. I think 3 reminders if enough for one poll, users can post the poll link if needed anyway.

**Comment by tinnvec** [comment]
6564992aa6863881fc6636564158cf012b1d3e2d closes this
